version: '3.8'

services:
  # Backend Laravel
  app: 
    image: laravel-app
    container_name: laravel-php82-container
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db-laravel
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=app
      - DB_PASSWORD=root_
      - VITE_DEV_SERVER_URL=http://host.docker.internal:5173
    depends_on:
      - db
    networks:
      - laravel-share-container

  # Base de datos MySQL
  db:
    image: mysql:8
    container_name: mysql-db-laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: app
      MYSQL_PASSWORD: root_
    ports:
      - "3320:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-share-container

  # Frontend Vite + React
  vite:
    image: node:20
    container_name: vite-container
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"  # Exponer el puerto 5173 del contenedor al host para Vite
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - app
    networks:
      - laravel-share-container

networks:
  laravel-share-container:
    driver: bridge

volumes:
  mysql-data:
    driver: local
